menu:
- {name: 'CV', url: '/cv'}
- {name: 'Blog', url: '/blog'}

social:
- {icon: 'github', link: 'https://matthewkhines.github.io'}
- {icon: 'twitter', link: 'contact'}
- {icon: 'instagram', link: 'contact'}
- {icon: 'linkedin', link: 'contact'}

